import { useState, useEffect, useCallback } from 'react'
import { useParams, useNavigate } from 'react-router-dom'
import Sidebar from '../../components/Sidebar'
import Button from '../../components/Button'
import { StatusBadge } from '../../components/Badge'
import Loading from '../../components/Loading'
import ErrorBanner from '../../components/ErrorBanner'
import { quotationService } from '../../services/quotation.service'
import { getErrorMessage } from '../../utils/errorHandler'

const fmtDate = (d) => d ? new Date(d).toLocaleString('en-GB') : '—'

export default function QuotationDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [quotation, setQuotation] = useState(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')

  const load = useCallback(async () => {
    setLoading(true); setError('')
    try {
      const data = await quotationService.get(id)
      setQuotation(data?.quotation || data)
    } catch (err) {
      setError(getErrorMessage(err))
    } finally { setLoading(false) }
  }, [id])

  useEffect(() => { load() }, [load])

  return (
    <div className="dashboard-layout">
      <div className={`sidebar-overlay${sidebarOpen ? ' open' : ''}`} onClick={() => setSidebarOpen(false)} aria-hidden="true" />
      <div className={sidebarOpen ? 'sidebar open' : 'sidebar'}>
        <Sidebar onClose={() => setSidebarOpen(false)} />
      </div>
      <main className="dashboard-main">
        <header className="dashboard-header">
          <div className="dashboard-header-left">
            <button className="mobile-menu-btn" aria-label="Open navigation" onClick={() => setSidebarOpen((v) => !v)}>☰</button>
            <div>
              <div className="dashboard-header-title">Quotation #{id.slice(0, 8)}</div>
              <div className="dashboard-header-sub">AI-Generated Quotation</div>
            </div>
          </div>
          <div className="dashboard-header-right">
            <Button variant="ghost" size="sm" onClick={() => navigate('/quotations')}>← Back</Button>
          </div>
        </header>

        <div className="dashboard-content" style={{ maxWidth: 800, margin: '0 auto' }}>
          {loading ? <Loading text="Loading quotation…" /> : error ? (
            <ErrorBanner message={error} onRetry={load} />
          ) : !quotation ? null : (
            <>
              {/* Pending approval banner */}
              {(quotation.status || '').toUpperCase() === 'PENDING_APPROVAL' && (
                <div style={{
                  background: '#fef3c7', border: '1px solid #fcd34d',
                  borderRadius: 'var(--radius-lg)', padding: 'var(--space-5)', marginBottom: 'var(--space-4)',
                  display: 'flex', gap: 12, alignItems: 'flex-start',
                }}>
                  <span style={{ fontSize: '1.5rem' }}>⏳</span>
                  <div>
                    <div style={{ fontWeight: 800, color: '#92400e', marginBottom: 4 }}>PENDING APPROVAL</div>
                    <p style={{ fontSize: 'var(--font-size-sm)', color: '#92400e', lineHeight: 1.6 }}>
                      This quotation was generated by AI. Human approval is required before any external action is taken.
                      Review the quotation below, then go to the enquiry to approve or reject.
                    </p>
                  </div>
                </div>
              )}

              <div className="card" style={{ marginBottom: 'var(--space-4)' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 16 }}>
                  <div>
                    <div style={{ fontWeight: 700, fontSize: 'var(--font-size-lg)', marginBottom: 4 }}>
                      {quotation.customer || quotation.enquiry?.customer || 'Customer Quotation'}
                    </div>
                    <div style={{ fontSize: 'var(--font-size-sm)', color: 'var(--color-text-muted)' }}>
                      Created: {fmtDate(quotation.createdAt)}
                    </div>
                  </div>
                  <StatusBadge status={(quotation.status || 'pending_approval').toLowerCase().replace(/ /g, '_')} />
                </div>

                {quotation.amount && (
                  <div style={{
                    background: 'var(--color-primary-soft)', border: '1px solid var(--color-primary-light)',
                    borderRadius: 'var(--radius-md)', padding: 'var(--space-4)', marginBottom: 16,
                    display: 'flex', alignItems: 'center', gap: 12,
                  }}>
                    <span style={{ fontSize: '1.5rem' }}>💰</span>
                    <div>
                      <div style={{ fontSize: 'var(--font-size-xs)', color: 'var(--color-primary-dark)', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.05em' }}>Quoted Amount</div>
                      <div style={{ fontWeight: 800, fontSize: 'var(--font-size-2xl)', color: 'var(--color-primary-dark)' }}>{quotation.amount}</div>
                    </div>
                  </div>
                )}

                <div style={{
                  background: 'var(--color-bg)', border: '1px solid var(--color-border)',
                  borderRadius: 'var(--radius-md)', padding: 'var(--space-4)',
                  fontSize: 'var(--font-size-sm)', lineHeight: 1.8, whiteSpace: 'pre-wrap', color: 'var(--color-text)',
                }}>
                  {quotation.content || quotation.description || 'No quotation content available.'}
                </div>

                <div style={{
                  marginTop: 16, padding: '8px 12px', background: '#fef3c7',
                  borderRadius: 'var(--radius-sm)', fontSize: 'var(--font-size-xs)', color: '#92400e',
                }}>
                  ⚠️ This is an <strong>AI-generated quotation</strong>. To approve or reject, go to the associated enquiry.
                </div>
              </div>

              {quotation.enquiryId && (
                <div style={{ display: 'flex', gap: 12 }}>
                  <Button variant="primary" onClick={() => navigate(`/enquiries/${quotation.enquiryId}`)}>
                    Go to Enquiry →
                  </Button>
                </div>
              )}
            </>
          )}
        </div>
      </main>
    </div>
  )
}
